#!groovy
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-agent-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi",
      resourceRequestCpu: "1",
      resourceLimitCpu: "2"
    )
  ]
) {
  node('skopeo-pod') {
    // Define Maven Command to point to the correct
    // settings for our Nexus installation
    def mvnCmd = "mvn -s ../nexus_settings.xml"

    // Checkout Source Code.
    stage('Checkout Source') {
      checkout scm
    }

    // Build the Tasks Service
    dir('openshift-tasks') {
      // The following variables need to be defined at the top level
      // and not inside the scope of a stage - otherwise they would not
      // be accessible from other stages.
      // Extract version from the pom.xml
      def version = getVersionFromPom("pom.xml")

      // Set the tag for the development image: version + build number
      def devTag  = "${version}-" + currentBuild.number
      // Set the tag for the production image: version
      def prodTag = "${version}"

      // Using Maven build the war file
      // Do not run tests in this step
      stage('Build war') {
        echo "Building version ${devTag}"
        // Execute Maven Build
        sh "${mvnCmd} clean package -DskipTests=true"
      }

      // TBD: The next two stages should run in parallel
      stage('Code Analysis & Unit Tests') {
        parallel (
          "Unit Tests" : {
            echo "Running Unit Tests"
            // Execute Unit Tests
            sh "${mvnCmd} test"
            step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
          },
          // Using Maven to call SonarQube for Code Analysis
          "Code Analysis": {
            echo "Running Code Analysis"
            // Execute Sonarqube Tests
            sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube.gpte-hw-cicd.svc.cluster.local:9000"
          }
        )
      }

      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"
        // Publish to Nexus
        sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.gpte-hw-cicd.svc.cluster.local:8081/repository/releases/"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image tasks:${devTag}"
        // Build Image, tag Image
        script {
          openshift.withCluster() {
            openshift.withProject("${GUID}-tasks-dev") {
              openshift.selector("bc", "tasks").startBuild("--from-file=./target/openshift-tasks.war", "--wait=true")
              // Tag the image using the devTag.
              openshift.tag("tasks:latest", "tasks:${devTag}")
            }
          }
        }
      }

    stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"
        script {
            // Update the Image on the Development Deployment Config
            openshift.withCluster() {
                openshift.withProject("${GUID}-tasks-dev") {
                    openshift.set("image", "dc/tasks", "tasks=docker-registry.default.svc:5000/${GUID}-tasks-dev/tasks:${devTag}")

                    // Update the Config Map which contains the users for the Tasks application
                    // (just in case the properties files changed in the latest commit)
                    openshift.selector('configmap', 'tasks-config').delete()
                    def configmap = openshift.create('configmap', 'tasks-config', '--from-file=./configuration/application-users.properties', '--from-file=./configuration/application-roles.properties' )

                    // Deploy the development application.
                    openshift.selector("dc", "tasks").rollout().latest();

                    openshift.set("env", "dc/tasks", "VERSION='${devTag} (tasks-dev)'", "--overwrite")

                    // Wait for application to be deployed
                    def dc = openshift.selector("dc", "tasks").object()
                    def dc_version = dc.status.latestVersion
                    def rc = openshift.selector("rc", "tasks-${dc_version}").object()

                    echo "Waiting for 'tasks' to appear in the curl response"
                    def tryAgain = true
                    def devTasksRoute = ""
                    while (tryAgain) {
                      devTasksRoute = sh(returnStdout: true, script: "curl tasks-${GUID}-tasks-dev.apps.${CLUSTER}").trim()
                      if (devTasksRoute.contains("tasks")) {
                        echo "*** tasks-dev validated successfully."
                        tryAgain = false
                      }
                      else {
                        echo "*** tasks-dev returned unexpected name."
                        sleep 5
                      }
                    }
                }
            }
        } 
    }

      // Copy Image to Nexus container registry
      stage('Copy Image to Nexus container registry') {
        echo "Copy image to Nexus container registry"
        script {

            // TBD: Copy image to Nexus container registry
            sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:redhat docker://docker-registry.default.svc.cluster.local:5000/${GUID}-tasks-dev/tasks:${devTag} docker://nexus-registry.gpte-hw-cicd.svc.cluster.local:5000/tasks:${devTag}"

            // TBD: Tag the built image with the production tag.
            openshift.withCluster() {
                openshift.withProject("${GUID}-tasks-prod") {
                openshift.tag("${GUID}-tasks-dev/tasks:${devTag}", "${GUID}-tasks-dev/tasks:${prodTag}")
                }
              }
          }
      }

      // Blue/Green Deployment into Production
      // -------------------------------------
      def destApp   = "tasks-green"
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
        // TBD: Determine which application is active
        //      Set Image, Set VERSION
        //      Deploy into the other application
        //      Make sure the application is running and ready before proceeding
        script {
            openshift.withCluster() {
                openshift.withProject("${GUID}-tasks-prod") {


                    activeApp = openshift.selector("route", "tasks").object().spec.to.name

                    echo "Active App ---> " + activeApp 

                    if (activeApp == "tasks-green") {
                        destApp = "tasks-blue"
                    }

                    echo "Active Application:        " + activeApp
                    echo "Defination Application:    " + destApp

                    // Update the Image on the Production Deployment Config 
                    def dc = openshift.selector("dc/${destApp}").object() 
                    dc.spec.template.spec.containers[0].image="docker-registry.default.svc:5000/${GUID}-tasks-dev/tasks:${prodTag}"
                    openshift.apply(dc)

                    // Update Config Map in change config files changed in the source
                    openshift.selector("configmap", "${destApp}-config").delete()
                    def configmap = openshift.create("configmap", "${destApp}-config", "--from-file=./configuration/application-users.properties", "--from-file=./configuration/application-roles.properties" )

                    // Deploy the inactive application 
                    openshift.selector("dc", "${destApp}").rollout().latest();

                    echo "Changing the name of the active app"
                    def route = openshift.selector("route/tasks").object()
                        route.spec.to.name = "${destApp}"
                        openshift.apply(route)
                    echo "New Active Application " + destApp

                    // Wait for application to be deployed
                    def dc_prod = openshift.selector("dc", "${destApp}").object()
                    def dc_version = dc_prod.status.latestVersion
                    def rc_prod = openshift.selector("rc", "${destApp}-${dc_version}").object()
                }
            }
        }
      }

      stage('Switch over to new Version') {
        echo "Switching Production application to ${destApp}."
        // TBD: Execute switch

        script {
          openshift.withCluster() {
            openshift.withProject("${GUID}-tasks-prod") {
              def route = openshift.selector("route/tasks").object()
              route.spec.to.name="${destApp}"
              openshift.apply(route)

              echo "Waiting for '${destApp}' to appear in the curl response"
              def tryAgain = true
              def tasksRoute = ""
              while (tryAgain) {
                tasksRoute = sh(returnStdout: true, script: "curl tasks-${GUID}-tasks-prod.apps.${CLUSTER}").trim()
                if (tasksRoute.contains("${destApp}")) {
                  echo "*** ${destApp} validated successfully."
                  tryAgain = false
                }
                else {
                  echo "*** ${destApp} returned unexpected name."
                  sleep 5
                }
              }
            }
          }
        }
      }
    }
  }
}

// Convenience Functions to read version from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}